services:
  - type: web
    name: cyber-ctr
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cyber-ctr-db
          property: connectionString
databases:
  - name: cyber-ctr-db
    databaseName: cyber_ctr
    user: cyber_ctr_user
